FROM python:3.11.2-alpine3.17
RUN apk update
RUN apk add git
COPY . /code
WORKDIR /code
ENV PYTHONUNBUFFERED 1
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
ARG PORT=80
ENV DB_USER=postgres
ENV DB_NAME=postgres
ENV DB_PORT=5432
VOLUME /code
EXPOSE 80
CMD python manage.py makemigrations && python manage.py migrate && python manage.py loaddata data_fixture.json && python manage.py runserver 0.0.0.0:$PORT 


# docker run --env-file env.txt -d -p 80:80  -v src:/code --name naruto_app naruto-api

### env.txt file format:
#DB_PASSWORD=test1234
#DB_HOST=localhost
#PORT=8000 optional, default=80
