# Generated by Django 4.1.5 on 2023-02-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_character_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='fr_name',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='description',
            new_name='fr_description',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='general_infos',
            new_name='fr_general_infos',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='fr_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='characters',
        ),
        migrations.AddField(
            model_name='category',
            name='en_characters',
            field=models.ManyToManyField(related_name='en_categories', to='api.character'),
        ),
        migrations.AddField(
            model_name='category',
            name='en_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='fr_characters',
            field=models.ManyToManyField(related_name='fr_categories', to='api.character'),
        ),
        migrations.AddField(
            model_name='character',
            name='en_description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='en_general_infos',
            field=models.JSONField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='en_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
