# Generated by Django 4.1.5 on 2023-02-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_category_fr_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='en_characters',
            field=models.ManyToManyField(null=True, related_name='en_categories', to='api.character'),
        ),
        migrations.AlterField(
            model_name='category',
            name='en_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='fr_characters',
            field=models.ManyToManyField(null=True, related_name='fr_categories', to='api.character'),
        ),
        migrations.AlterField(
            model_name='category',
            name='fr_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='en_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='en_general_infos',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='en_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='fr_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='fr_general_infos',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='fr_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
