# Generated by Django 4.1.5 on 2023-02-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_en_characters_alter_category_en_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='en_characters',
            field=models.ManyToManyField(related_name='en_categories', to='api.character'),
        ),
        migrations.AlterField(
            model_name='category',
            name='fr_characters',
            field=models.ManyToManyField(related_name='fr_categories', to='api.character'),
        ),
    ]
