# Generated by Django 4.1.5 on 2023-02-14 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_category_en_characters_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='fr_characters',
            new_name='characters',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='en_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='en_characters',
        ),
        migrations.RemoveField(
            model_name='category',
            name='fr_name',
        ),
    ]
